blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://stackoverflow.com/questions/ask?tags=gtsummary,r
    about: Question must include a minimal reproducible example, aka a <a href="https://reprex.tidyverse.org/" target="_blank">reprex</a>.
